"""Shared software-only telemetry envelope validation."""

from .envelope import (
    CANONICAL_TELEMETRY_EVENT_NAMES,
    DIAGNOSTIC_FIELDS,
    FIRMWARE_TELEMETRY_EVENT_SCHEMA_ID,
    FIRMWARE_TELEMETRY_REPORT_SCHEMA_ID,
    IDENTITY_FIELDS,
    OBSERVABILITY_CONTRACT_EVENT_NAMES,
    OBSERVABILITY_TELEMETRY_CONTRACT_ID,
    REQUIRED_ENVELOPE_FIELDS,
    TELEMETRY_EVENT_SCHEMA_ID,
    TELEMETRY_EVENT_SCHEMA_VERSION,
    TELEMETRY_REPLAY_SUMMARY_KEYS,
    TELEMETRY_SEVERITIES,
    TelemetryEnvelope,
    TelemetryEnvelopeError,
    TelemetryEnvelopeValidation,
    TelemetryReplaySummary,
    make_telemetry_envelope,
    normalize_telemetry_envelope,
    project_firmware_telemetry_report_events,
    telemetry_canonical_sha256,
    telemetry_envelope_from_mapping,
    validate_telemetry_event_name,
    validate_firmware_telemetry_reports,
    validate_telemetry_envelope,
    validate_telemetry_records,
)

__all__ = [
    "CANONICAL_TELEMETRY_EVENT_NAMES",
    "DIAGNOSTIC_FIELDS",
    "FIRMWARE_TELEMETRY_EVENT_SCHEMA_ID",
    "FIRMWARE_TELEMETRY_REPORT_SCHEMA_ID",
    "IDENTITY_FIELDS",
    "OBSERVABILITY_CONTRACT_EVENT_NAMES",
    "OBSERVABILITY_TELEMETRY_CONTRACT_ID",
    "REQUIRED_ENVELOPE_FIELDS",
    "TELEMETRY_EVENT_SCHEMA_ID",
    "TELEMETRY_EVENT_SCHEMA_VERSION",
    "TELEMETRY_REPLAY_SUMMARY_KEYS",
    "TELEMETRY_SEVERITIES",
    "TelemetryEnvelope",
    "TelemetryEnvelopeError",
    "TelemetryEnvelopeValidation",
    "TelemetryReplaySummary",
    "make_telemetry_envelope",
    "normalize_telemetry_envelope",
    "project_firmware_telemetry_report_events",
    "telemetry_canonical_sha256",
    "telemetry_envelope_from_mapping",
    "validate_telemetry_event_name",
    "validate_firmware_telemetry_reports",
    "validate_telemetry_envelope",
    "validate_telemetry_records",
]
