"""Pure focus-metric replay projection and hash helpers."""

from .projections import (
    CALIBRATION_PROJECTION_FIELDS,
    COMPRESSED_ENCODINGS,
    FRAME_METADATA_PROJECTION_FIELDS,
    LINEAR_DOMAINS,
    NONLINEAR_TRANSFORMS,
    OFFLINE_REJECTION_CODES,
    RAW_FORMATS,
    REJECTION_CODES,
    REQUIRED_CALIBRATION_ROLES,
    SOURCE_PROJECTION_FIELDS,
    calibration_matches_registry,
    calibration_reference_sha256,
    canonical_sha256,
    focus_metric_result_sha256,
    manifest_rejection_codes,
    missing_calibration_id_rejection_codes,
    metric_config_sha256,
    replay_decision_sha256,
    source_frame_rejection_codes,
    selected_calibration_fields,
    selected_frame_metadata_fields,
    selected_source_fields,
    source_frame_checksum,
)

__all__ = [
    "CALIBRATION_PROJECTION_FIELDS",
    "COMPRESSED_ENCODINGS",
    "FRAME_METADATA_PROJECTION_FIELDS",
    "LINEAR_DOMAINS",
    "NONLINEAR_TRANSFORMS",
    "OFFLINE_REJECTION_CODES",
    "RAW_FORMATS",
    "REJECTION_CODES",
    "REQUIRED_CALIBRATION_ROLES",
    "SOURCE_PROJECTION_FIELDS",
    "calibration_matches_registry",
    "calibration_reference_sha256",
    "canonical_sha256",
    "focus_metric_result_sha256",
    "manifest_rejection_codes",
    "missing_calibration_id_rejection_codes",
    "metric_config_sha256",
    "replay_decision_sha256",
    "source_frame_rejection_codes",
    "selected_calibration_fields",
    "selected_frame_metadata_fields",
    "selected_source_fields",
    "source_frame_checksum",
]
